# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Cmake\cmake-3.28.1\bin\cmake.exe

# The command to remove a file.
RM = D:\Cmake\cmake-3.28.1\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Desktop\BirdPass

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Desktop\BirdPass

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\Cmake\cmake-3.28.1\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\Cmake\cmake-3.28.1\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Desktop\BirdPass\CMakeFiles D:\Desktop\BirdPass\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Desktop\BirdPass\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BirdPass

# Build rule for target.
BirdPass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BirdPass
.PHONY : BirdPass

# fast build rule for target.
BirdPass/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/build
.PHONY : BirdPass/fast

src/AES.obj: src/AES.cpp.obj
.PHONY : src/AES.obj

# target to build an object file
src/AES.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/AES.cpp.obj
.PHONY : src/AES.cpp.obj

src/AES.i: src/AES.cpp.i
.PHONY : src/AES.i

# target to preprocess a source file
src/AES.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/AES.cpp.i
.PHONY : src/AES.cpp.i

src/AES.s: src/AES.cpp.s
.PHONY : src/AES.s

# target to generate assembly for a file
src/AES.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/AES.cpp.s
.PHONY : src/AES.cpp.s

src/Deco.obj: src/Deco.cpp.obj
.PHONY : src/Deco.obj

# target to build an object file
src/Deco.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/Deco.cpp.obj
.PHONY : src/Deco.cpp.obj

src/Deco.i: src/Deco.cpp.i
.PHONY : src/Deco.i

# target to preprocess a source file
src/Deco.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/Deco.cpp.i
.PHONY : src/Deco.cpp.i

src/Deco.s: src/Deco.cpp.s
.PHONY : src/Deco.s

# target to generate assembly for a file
src/Deco.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/Deco.cpp.s
.PHONY : src/Deco.cpp.s

src/OS.obj: src/OS.cpp.obj
.PHONY : src/OS.obj

# target to build an object file
src/OS.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/OS.cpp.obj
.PHONY : src/OS.cpp.obj

src/OS.i: src/OS.cpp.i
.PHONY : src/OS.i

# target to preprocess a source file
src/OS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/OS.cpp.i
.PHONY : src/OS.cpp.i

src/OS.s: src/OS.cpp.s
.PHONY : src/OS.s

# target to generate assembly for a file
src/OS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/OS.cpp.s
.PHONY : src/OS.cpp.s

src/TOTP.obj: src/TOTP.cpp.obj
.PHONY : src/TOTP.obj

# target to build an object file
src/TOTP.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/TOTP.cpp.obj
.PHONY : src/TOTP.cpp.obj

src/TOTP.i: src/TOTP.cpp.i
.PHONY : src/TOTP.i

# target to preprocess a source file
src/TOTP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/TOTP.cpp.i
.PHONY : src/TOTP.cpp.i

src/TOTP.s: src/TOTP.cpp.s
.PHONY : src/TOTP.s

# target to generate assembly for a file
src/TOTP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/TOTP.cpp.s
.PHONY : src/TOTP.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sm4.obj: src/sm4.cpp.obj
.PHONY : src/sm4.obj

# target to build an object file
src/sm4.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/sm4.cpp.obj
.PHONY : src/sm4.cpp.obj

src/sm4.i: src/sm4.cpp.i
.PHONY : src/sm4.i

# target to preprocess a source file
src/sm4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/sm4.cpp.i
.PHONY : src/sm4.cpp.i

src/sm4.s: src/sm4.cpp.s
.PHONY : src/sm4.s

# target to generate assembly for a file
src/sm4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BirdPass.dir\build.make CMakeFiles/BirdPass.dir/src/sm4.cpp.s
.PHONY : src/sm4.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... BirdPass
	@echo ... src/AES.obj
	@echo ... src/AES.i
	@echo ... src/AES.s
	@echo ... src/Deco.obj
	@echo ... src/Deco.i
	@echo ... src/Deco.s
	@echo ... src/OS.obj
	@echo ... src/OS.i
	@echo ... src/OS.s
	@echo ... src/TOTP.obj
	@echo ... src/TOTP.i
	@echo ... src/TOTP.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/sm4.obj
	@echo ... src/sm4.i
	@echo ... src/sm4.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

